resolver: lts-7.13

packages:
- '.'

extra-deps:
- haskell-src-exts-1.19.1
- s-cargot-0.1.1.1
# - sexp-grammar-1.2.2
# - haskell-src-exts-1.18.2
# - haskell-src-exts-prisms-1.18.2.0

flags: {}

extra-package-dbs: []
